FROM debian:bullseye

RUN apt-get update -y

RUN apt-get install curl -y

RUN curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
RUN chmod +x bootstrap-salt.sh
RUN ./bootstrap-salt.sh -M -N

RUN apt-get install python3-pygit2 -y

ENTRYPOINT ["salt-master", "-l", "debug"]
